@isTest
private class AccountServiceTest {
    // @isTest
//     static void should_create_account(){
//         String accName = 'Salesforce';
//         String accNum = 'SFDC';
//         String ticket = 'CRM';
// Test.startTest();
// AccountService service = new AccountService();
// Account newAcc = service.createAccount(accName, accNum, ticket);
// insert newAcc;
// Test.stopTest();
// List<Account> acc = [SELECT ID, Name , AccountNumber , TicketSymbol FROM Account WHERE ID= :newAcc.Id ];
// System.assertEquals(1, acc.size(), 'Should have found new Accout');
// System.assertEquals(accName, acc[0].Name, 'incorrect Name');
// System.assertEquals(accNum, acc[0].AccountNumber, 'incorrect Account Number');
// System.assertEquals(ticket, acc[0].TickerSymbol, 'incorrect Ticket');
//     }

/*
TOGGLE CHECKPOINTS 
UPDTAE CHECKPOINTS
TURN ON APEX REPLAY DEBUGGER
GET APEX DEBEUG LOG

*/
}